sonar.projectKey=EPM-INAI-step-ui
sonar.qualitygate.wait=true
sonar.junitReportPaths=junit.xml
sonar.sources=src
sonar.exclusions=src/__test__/**, src/assets/**,src/__mock__/**, **/*.css, **/index.js, **/main.js, **/app.js, **/reportWebVitals.js, **/setupTests.js, **/babel.config.js, **/jest.config.js, package-lock.json, package.json, src/components/utils/**, src/components/common/axios.js,src/components/styling**

sonar.tests=src/__test__
sonar.testExecutionReportPaths=test-report.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info